#!/usr/bin/env python
import os

top = '.'
out = 'build'

def options(opt):
    if os.name != 'nt':
        opt.load('compiler_c')

def configure(conf):
    if os.name != 'nt':
        conf.load('compiler_c')
    else:
        conf.env['MSVC_VERSIONS'] = ['msvc 15']
		conf.load('msvc')

def build(ctx):
    _cflg = '' if os.name == 'nt' else '-fPIC'
    ctx.objects(source='SPTK/bin/fft/_fft.c SPTK/lib/getmem.c SPTK/lib/movem.c SPTK/lib/fillz.c SPTK/bin/mgcep/_mgcep.c SPTK/bin/mlsadf/_mlsadf.c SPTK/bin/b2mc/_b2mc.c SPTK/bin/gc2gc/_gc2gc.c SPTK/bin/gnorm/_gnorm.c SPTK/bin/ifftr/_ifftr.c SPTK/bin/fftr/_fftr.c  SPTK/bin/ifft/_ifft.c SPTK/bin/ignorm/_ignorm.c SPTK/bin/mc2b/_mc2b.c  SPTK/lib/theq.c', includes='SPTK/include', target='sptk', features='c', cflags=_cflg)

    ctx.shlib(source='VCLib.c', includes='SPTK/include ../include', use='sptk', target='vclib', features='c')
